- name: Configuring Mongodb Setup 
  hosts: mongodb
  become: yes 
  tasks:

  - name : Copying mongodb repo 
    copy:
      scr: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
 
  - name : Installing Mongodb
    package:
      name: mongodb-org
      state: present 

  - name : Start and enabling Mongodb service
    service:
      name: mongod
      state: started
      enabled: yes
    
  - name : Allowing remote connection 
    replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name : Restarting the Mongodb service
    service:
      name: mongod
      state: restarted