- name: user
  hosts: user
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install nodejs
    dnf:
      name: nodejs 
      state: present

  - name: create roboshop user
    user:
      name: roboshop

  - name: Recursively remove app directory
    file:
      path: /app
      state: absent

  - name: create app directory
    file:
      path: /app
      state: directory

  - name: download user application
    get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: extract user application
    unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    command: npm install
    args:
      chdir: /app

  - name: Copy user service
    copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: deamon realod and start
    systemd_service:
      daemon_reload: true

  # let's start after the data is loaded

  - name: Copy mongodb repo
    copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb client
    package:
      name: mongodb-org-shell
      state: present

  - name: get the users count
    command:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  # - name: print the count
  #   debug:
  #     msg: "product count: {{user_count}}"

  - name: load user data
    command: mongo --host mongodb.daws76s.online < /app/schema/user.js
    when: user_count.stdout == "0" # keep double quotes

  - name: start and enable user
    service:
      name: user
      state: restarted
      enabled: yes